### ISSUE TITLE
Disappearing text when editing paragraph that has line breaks

### ISSUE THREAD

**Issue by cruzanmo** [clay/clay-kiln#1040] opened 2017-12-03 00:26 UTC
## Bug
When a paragraph has one block of text followed by 2 line breaks and then another block of text, clicking to edit the paragraph hides the second block of text, however after hitting the `enter` key, kiln properly creates two paragraphs with the text that is visible and the text that is hidden appears in the second paragraph.

Here is an example that had this issue: HTML from rendered component (sorry, did not grab the component data before fixing).
```<p class="clay-paragraph" data-editable="text" data-uri="www.vulture.com/components/clay-paragraph/instances/cjaod3bjr000w3i5x4ki5sskd" data-word-count="146" style=""><em>Alien: Covenant </em>(2017)<br><em>Child of God </em>(2013)<br><em>The Dead Girl </em>(2006)<br><em>Deuces Wild</em> (2002)<br><em>Finishing the Game</em> (2007)<br><em>The Green Hornet</em> (2011)<br><em>The Holiday</em> (2006)<br><em>Interview </em>(2007)<br><em>Knocked Up </em>(2007)<br><em>The Little Prince</em> (2015)<br><em>Lovelace</em> (2013)<br><em>Mother Ghost </em>(2002)<br><em>Never Been Kissed </em>(1999)<br><em>The Night Before </em>(2016)<br><em>Nights in Rodanthe</em> (2008)<br><em>Sal </em>(2011)<br><em>Sausage Party</em> (2016)<br><em>The Vault</em> (2017)<br><em>Veronica Mars </em>(2013)<br><em>The Wicker Man </em>(2006)<br><em>You Always Stalk the Ones You Love</em> (2002)<br><br>That leaves us with 36 Actual Movies that Franco has appeared in, giving relatively normal, human-actor performances. In these movies, you get some actual clarity as to what kind of an actor Franco really is. He’s smart, he’s daring, but he’s also a little guarded: He can sometimes come across like more of a <em>concept </em>of an actor than an actual actor. Which is why those little moments when he lets himself show are so powerful: There’s charisma and humanity and soul there, and not even Franco can hide it all the time.</p>```

**Comment by nelsonpecora** [comment] 2017-12-04 14:39
dupe of #987

**Closed by nelsonpecora** 2017-12-04 14:39 UTC
