### ISSUE TITLE
Articles Show The Are Scheduled After They Publish

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1108] opened 2018-02-05 16:34 UTC
These articles were published and the editor says that a new scheduled time was not set for them, but the status in Kiln still shows Scheduled. 

Here are two examples where this is happening: 

* http://nymag.com/press/2018/02/mary-j-blige-covers-new-yorks-spring-fashion-issue.html?edit=true
* http://www.grubstreet.com/2018/02/chef-gerardo-gonzalez-grub-street-diet.html?edit=true

**Comment by pfeytser** [comment] 2018-02-08 14:24
Another one reported today:
https://www.thecut.com/article/6-ways-to-feel-good-about-being-single.html?edit=true

**Comment by amycheng** [comment] 2018-02-08 16:23
A solution would be to remove the `Scheduled` property from pages when are published. However, this would prevent published articles that are regularly updated to be scheduled. But maybe Kiln can ignore this use case?

**Comment by pfeytser** [comment] 2018-02-14 20:31
Difficult to debug without logging, need ELK implemented first.

**Comment by pfeytser** [comment] 2018-05-03 18:31
Email from producer on scheduling problems:

The copy editors and I have noticed pretty consistent, issues with scheduling in Clay over the past few months. Sometimes scheduled posts fail to go up, other times you schedule a post but it still publishes immediately, and often times scheduled posts fail to update their status to 'published' in Clay, which makes it difficult to republish them if we need to make an update/correction. 

Here are some examples: 

Published but still showing status 'scheduled' or 'draft' (this happens a LOT) 
http://nymag.com/travel/_pages/cjfkgqd3c00adr5y636y2uya8.html?edit=true#
http://www.vulture.com/_pages/cjgmpucrm00x20ey68cyfh63y.html?edit=true

Scheduled but published when copy editor hit the 'schedule' button (had to be unpubbed and rescheduled) 
http://www.vulture.com/_pages/cjgmpucrm00x20ey68cyfh63y.html?edit=true
http://nymag.com/daily/intelligencer/2018/02/americas-opioid-epidemic.html

Scheduled but failed to publish and had to be manually published: 
https://www.thecut.com/_pages/cjfsoaplc0000kmyee6x28h0t.html?edit=true
https://www.thecut.com/2018/04/can-a-male-artist-still-paint-a-female-nude.html

And this is probably the weirdest one I've come across -- it initially wouldn't let me schedule it. Then Reuben did something to fix it. But it went up at 9am instead of 9pm (which is what I scheduled it for). And then when I tried to make an update several days later, it was showing as a 'draft' and wouldn't let me repub 
http://www.vulture.com/2018/04/john-krasinski-a-quiet-place.html?edit=true

**Comment by nelsonpecora** [comment] 2018-05-08 16:57
Cool, that's a lot of good info. Let's see if we can break these down:

**Group A** (published, but still showing scheduled) I think is caused by pages that have been _published via amphora_ (i.e. not kiln) not triggering the `unschedulePage` hook for amphora-search. That can be fixed by an amphora patch.

**Group B** (scheduled, but published immediately) doesn't show such a distinct pattern, so let's look at them separately.

**B.1** (Saoirse Ronan) looks like a case of two users colliding. Trupti and Jonann were both editing the page, and it looks like they both tried to schedule it and some wires got crossed. I can't tell if that was user error (scheduling "immediately") but something's up.

<img width="317" alt="screen shot 2018-05-08 at 12 42 07 pm" src="https://user-images.githubusercontent.com/447522/39770589-79f331c6-52bd-11e8-8d55-c38e6ef19580.png">

**B.2** (Sullivan) looks like it was scheduled on the 18th, then manually published, unpublished, edited, and republished over the following days.

<img width="316" alt="screen shot 2018-05-08 at 12 48 18 pm" src="https://user-images.githubusercontent.com/447522/39770827-2a5c061e-52be-11e8-9edc-9efd92d63d38.png">

**Group C** (scheduled but failed to publish) also doesn't show a distinct pattern.

**C.1** (talking about skincare online) looks like it was never actually scheduled (or the scheduling didn't trigger the `schedulePage` hook), but there's a suspicious "published by clay" after it was manually published.

<img width="315" alt="screen shot 2018-05-08 at 12 50 30 pm" src="https://user-images.githubusercontent.com/447522/39770988-ae32fb46-52be-11e8-9f66-019ea2a1fddd.png">

**C.2** (male artists) looks like it _was_ scheduled, but then manually published, edited, unpublished, and republished over the next two days

<img width="314" alt="screen shot 2018-05-08 at 12 53 38 pm" src="https://user-images.githubusercontent.com/447522/39771090-fdba3cf6-52be-11e8-930b-756e1366d5f8.png">

The last one looks like it was scheduled and published correctly, then edited and republished over the course of two days. I don't see any evidence that Reuben or you did anything to it (including scheduling it). @reubenson thoughts?

<img width="319" alt="screen shot 2018-05-08 at 12 55 29 pm" src="https://user-images.githubusercontent.com/447522/39771200-4eddc378-52bf-11e8-9860-d3bbfbb62a4f.png">

**Comment by nelsonpecora** [comment] 2018-05-08 17:29
Actually, I'm not sure what's happening with Group A. Locally, it was sending the `unschedulePage` hook perfectly even on clay-published pages.

**Comment by nelsonpecora** [comment] 2018-05-08 18:03
Blerg, I'm not sure what's happening on prod because I can't reproduce any issues locally. All of these examples are older than our logs, so I can't see if there was some kind of error on production when they were scheduled / published.

**Comment by nelsonpecora** [comment] 2018-05-09 21:06
#1205 doesn't completely fix this issue, but it should prevent some of the "I hit schedule but it published immediately" error cases.

**Comment by nelsonpecora** [comment] 2018-05-14 14:44
Putting this in review until we get more feedback on the #1205 fix

**Comment by nelsonpecora** [comment] 2018-05-21 19:12
Have there been any more instances of this since the #1205 fix went live?

**Closed** 2018-05-22 17:38 UTC
Labels: api, bug, ux
