### ISSUE TITLE
Bug: New Material Design: Blockquote

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#969] opened 2017-11-03 16:25 UTC
## Bug
1) Go to feature branch, create an article
2) click to add blockquote component, note it throws an error

![image](https://user-images.githubusercontent.com/4931851/32384659-fedfdfec-c091-11e7-94ac-bd75ee97f7a5.png)

![blockquote](https://user-images.githubusercontent.com/4931851/32384674-07374662-c092-11e7-8a70-a47600b7a7e3.png)

**Comment by nelsonpecora** [comment] 2017-11-03 17:29
I can't reproduce this locally. It may have been fixed by the schema change I did for #968

**Closed by nelsonpecora** 2017-11-03 17:29 UTC
