### ISSUE TITLE
Bug: Glitch in editing multi-graf clay-paragraph component

### ISSUE THREAD

**Issue by cperryk** [clay/clay-kiln#987] opened 2017-11-09 14:51 UTC
A user reported this problem. A paragraph component had this text data:

`
I felt powerless through it all​. B​eing young and pregnant ​meant a lot of societal judgment. I wasn’t in high school, but I wasn’t married, and the feeling was very much: If you’re young and pregnant, you’re stupid. That’s how we look at young parents. I don’t advocate for teenagers getting pregnant, but using teen pregnancy to determine how well a society is doing — that’s evidence of the stigma. I just wish I’d had someone to cheerlead for me, to tell me that I was strong enough to do it. Instead, I was lonely. Still, I never thought I made the wrong decision.<br /><br /><br /><strong>On the upside of a car accident. </strong>My maternity leave was only six weeks, so I had to go back to work when my daughter was 5 weeks old. With my commute I’d be gone 10, 12 hours — the whole breastfeeding thing didn’t last very long. ​So not only did I feel guilty about being away all day, but already I hadn’t been able to fulfill what I considered an important “good mom” goal.
`

When attempting to edit the graf starting with `On the upside of a car accident...` by clicking it, that graf would disappear from the UI, and not be editable, though you could still edit the _first_ graf. When clicking out of the component, the second graf would reappear.

The user said this graf was likely pasted in from a Google Doc.

**Comment by nelsonpecora** [comment] 2017-11-09 14:54
Hmm. Where were they pasting from? Those three `<br>` tags should have triggered new paragraph creation, since the paragraphs are using `multi-component` wysiwyg

**Comment by cperryk** [comment] 2017-11-09 15:02
@nelsonpecora [This Google Doc](https://docs.google.com/document/d/1uWgzRv5P0quTIssCOJB6eU2s2b5vlf3Z7ANYeaAqz3M/edit?usp=sharing)

**Comment by nelsonpecora** [comment] 2017-11-09 16:24
That doc pastes correctly for me in Chrome on Kiln 5.0.1

![screen shot 2017-11-09 at 11 23 49 am](https://user-images.githubusercontent.com/447522/32616560-9b800b4e-c540-11e7-9247-fa1197fbb25b.png)

**Comment by cperryk** [comment] 2017-11-09 17:37
@nelsonpecora I'm still seeing this on Kiln 5.0.2. Here are exact steps to reproduce:

1. Create a new article.
2. Copy and paste complete Google Doc text into first clay-paragraph component.
3. Mouse over to the graf starting with "On moving forward with relationship." (Notice that it is within the same clay-paragraph component as the above graph.)
4. Click that graf, edit it in any way, and then click out.
5. Click the graf again, and it disappears. It's impossible to edit. Click out, and it reappears.

**Comment by nelsonpecora** [comment] 2017-11-09 18:20
Ah, thanks for the detailed steps. It looks like the issue is that the line breaks are interspersed with formatting, in a weird way.

![](http://up.keats.me/3a3m3R1F2U1F/Screen%20Shot%202017-11-09%20at%201.18.26%20PM.png)

**Comment by nelsonpecora** [comment] 2017-11-14 21:05
I can't really see a way for us to handle this, since that's technically valid code. Got any ideas?

**Comment by pfeytser** [comment] 2017-11-16 20:56
Won't fix, will re-open if this happens again.

**Comment by nelsonpecora** [comment] 2017-12-04 14:40
Looks like this isn't a one-off. @pfeytser @amycheng any ideas how we should handle it?

**Comment by pfeytser** [comment] 2017-12-12 20:58
Can't figure out a solution for this, but it's infrequent enough that we'll fix it manually when it comes up.

**Closed by pfeytser** 2017-12-12 20:58 UTC
Labels: bug, wontfix
