### ISSUE TITLE
Bug: New Material Design: Video

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#970] opened 2017-11-03 16:28 UTC
## Bug
1) Create a new article
2) add video component, not it throws an error 

![image](https://user-images.githubusercontent.com/4931851/32384817-83509046-c092-11e7-98be-9e48fa74522e.png)

![videocomponent](https://user-images.githubusercontent.com/4931851/32384830-8bf7dc2c-c092-11e7-83bc-bf1de553f0dd.png)

**Comment by nelsonpecora** [comment] 2017-11-03 17:31
I cannot reproduce this locally. I may have been fixed by the same change that fixed #969

**Closed by nelsonpecora** 2017-11-03 17:31 UTC
