### ISSUE TITLE
No Title showing in the All Pages list instead of the actual article titles

### ISSUE THREAD

**Issue by terrineal** [clay/clay-kiln#1216] opened 2018-05-15 20:15 UTC
## Bug
An editor noticed that in the All Pages list in Clay that a lot of articles (drafts and published) had _No Title_ instead of the actual article title.

**Comment by nelsonpecora** [comment] 2018-05-21 20:25
duplicate of https://github.com/clay/clay-kiln/issues/1215

**Closed by nelsonpecora** 2018-05-21 20:25 UTC
