### ISSUE TITLE
Bug: Complex list buttons show inconsistently

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1056] opened 2017-12-11 16:42 UTC
## Bug
The buttons to add/remove items from a complex list seem to require a mouse click to show. This is an issue when the first item is added to a list and the buttons are not visible until the user clicks into a field. When there is only one field for an item, or if the user moves between fields using the keyboard, the buttons to add another item are not available.

**Comment by nelsonpecora** [comment] 2017-12-12 15:29
This is by design, because the previous way (listening for focus changes and using that to switch items) was inconsistent, but you're right that it does present issues when tabbing through forms quickly. Let's investigate if there's a more stable way to add `focus`/`blur` handling as a secondary affordance to the clicking.

**Comment by nelsonpecora** [comment] 2018-04-02 16:01
I couldn't find a consistent way to allow both affordances. Feel free to take a crack at it, but I'm going to close this ticket unless it becomes high priority.

**Closed by nelsonpecora** 2018-04-02 16:01 UTC
Labels: feature, ux, wontfix
